---
- name: Enable filebeat service and ensure it is not masked
  ansible.builtin.systemd:
    name: "{{ wares_lan_filebeat_service.filename }}"
    enabled: true
    daemon_reload: true
    masked: no

- name: Restart filebeat service
  ansible.builtin.service:
    name: "{{ wares_lan_filebeat_service.filename }}"
    state: restarted
